test:
  - changed-files:
    - any-glob-to-any-file: __tests__/**/*
bin:
  - changed-files:
    - any-glob-to-any-file: bin/**/*
application:
  - changed-files:
    - any-glob-to-any-file: src/**/*
github:
  - changed-files:
    - any-glob-to-any-file: .github/**/*
